- hosts: all
  become: yes
  pre_tasks:
    # Shared logic included here with pre-tasks
    - name: include global_vars.yml
      include_vars: ./vars/global.yml

    - name: include morpheus/global vars file
      include_vars: ./vars/morpheus_vars.yml

    - debug:
        msg:
          - "Logging Variables from vars in project"
          - "Ansible Distro Verison - {{ ansible_distribution_version }}"
          - "Custom Hostname - {{ custom_hostname }}"
          - "m_cloud_code: {{ m_cloud_code }}"
          - "m_cloud_region: {{ m_cloud_region }}"
          - "m_cloud_name: {{ m_cloud_name }}"
          - "m_instance_context: {{ m_instance_context }}"
          - "m_instance_type_code: {{ m_instance_type_code }}"
          - "m_instance_type_name: {{ m_instance_type_name }}"
          - "m_created_by: {{ m_created_by }}"
          - "m_group_code: {{ m_group_code }}"
          - "m_description: {{ m_description }}"
          - "isRHEL7: {{ isRHEL7 }}"
          - "isCENTOS7_Lab: {{ isCENTOS7_Lab }}"
          - "isUBUNTU_Lab: {{ isUBUNTU_Lab }}"
