---
- hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: Print out all morpheus vars
    debug: 
      msg: 
      - "This is the morpheus json vars"
      - "{{ morpheus }}"


  - name: Dump morpheus variable for this instance
    debug:
      msg: "{{ hostvars[inventory_hostname]['morpheus'] | to_nice_yaml }}"