---
- hosts: all
  become: true
  gather_facts: no
  tasks:
  - name: Print out all morpheus vars
    debug: 
      msg: 
      - "This is the morpheus json vars"
      - "{{ morpheus | to_nice_yaml}}"