---
- name: Printing Test
  hosts: all
  become: True
  pre_tasks:      
    - name: include morpheus_vars.yml
      include_vars: ./vars/morpheus_vars.yml
  tasks:

  - name: Print out cypher
    debug: 
      msg: "This is a secret from Cypher: {{ lookup('cypher','secret=secret/test') }}"

  - name: Print out morpheus varable
    debug:
      msg: "This is a morpheus variable: {{ morpheus['instance']['hostname'] }}"

  - name: Print out the morpheus variable from the ./vars/morpheus_vars.yml file
    debug: "Thist is a morpheus variable from the morepheus.yml vars in the project: {{ m_instance.hostname }}"