- name: Add the Docker-CE reposoitory
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    update_cache: yes
    state: present

- name: Install Docker-CE
  package:
    name: "{{ docker_ce_packages }}"
    state: latest

- name: Start and Enable Docker service
  service: 
    name: docker
    state: started
    enabled: True